-language: generic
-sudo: false
-addons:
-  apt:
-    packages:
-      - libc6-i386
-      - libgcc1:i386
-      - libstdc++6:i386
-      - python
-      - python-pip
-
-install:
-  - travis/install_build_tools.sh
-
-before_script:
-  - travis/before_build_tools.sh
-  - travis/before_build_byond.sh
-
-script:
-  - travis/check_filedirs.sh yogstation.dme
-  - travis/build_tools.sh
-  - travis/build_byond.sh